import type { ProductData } from "@/types/product";

// Product content extracted from daswell.com. Generated by scripts/gen-products.py.
export const products: Record<string, ProductData> = {
  "concrete-mixer-pump": {
    "slug": "concrete-mixer-pump",
    "title": "Concrete Mixer Pump",
    "breadcrumb": [
      { "text": "Home", "href": "/" },
      { "text": "Concrete Pumps", "href": "/concrete-pumps/" },
      { "text": "Concrete Mixer Pump" }
    ],
    "intro": {
      "paragraphs": [
        "A concrete mixer pump puts batching, mixing, and pipeline placement on one trailer-mounted chassis. Instead of running a separate mixer plus a line pump—and the crews, space, and handoffs that come with them—you produce concrete on site and push it through the pipeline in a continuous cycle.",
        "KEWAN mixer pumps are built for contractors who work where ready-mix trucks are scarce, access is tight, or daily pours do not justify two full machines. Typical uses include low- to mid-rise housing, rural roads and bridges, plant floors, tunnels, and renovation jobs that still need reliable pumping distance.",
        "Choose diesel for off-grid or unstable power, or electric where grid supply is solid. With remote control, a compact footprint, and steady hydraulic delivery, the unit is designed to cut labor, shorten pours, and keep quality consistent from batch to batch."
      ],
      "keySpecs": [
        { "label": "Max. theoretical output", "value": "35–45 m³/h" },
        { "label": "Outlet pressure", "value": "12 MPa" },
        { "label": "Power options", "value": "Diesel / Electric" }
      ],
      "image": "/images/2025/03/concrete-mixer-pump.png",
      "imageAlt": "KEWAN concrete mixer pump on construction site",
      "buttons": [
        { "text": "Get a Quote", "href": "#request-quote" },
        { "text": "WhatsApp", "href": "https://wa.me/8615700731570" },
        { "text": "Send Email", "href": "mailto:global@kewan.com" }
      ]
    },
    "featureBlocks": [
      {
        "heading": "One machine: mix on site, pump where the pour is",
        "paragraphs": [
          "On many small and mid-size sites, the bottleneck is not mixing or pumping alone—it is moving wet concrete between two machines. A KEWAN concrete mixer pump closes that gap: aggregates, sand, cement, and water are charged into the mixer; when the batch is ready, concrete drops into the pumping hopper and is delivered through the pipeline under hydraulic pressure.",
          "That single workflow is especially useful where commercial ready-mix is expensive or unavailable, roads cannot take full mixer trucks, or you need to adjust mix proportions on the spot. Load with a small wheel loader or excavator, operate the mixer and pump from one remote, and keep the pour moving without waiting on a separate mixer fleet."
        ],
        "image": "/images/2025/04/main-parts-details-of-concrete-mixer-pump.jpg",
        "imageAlt": "Concrete mixer pump main components and layout"
      },
      {
        "heading": "Where contractors put mixer pumps to work",
        "paragraphs": [
          "Mixer pumps earn their keep when flexibility matters more than raw plant capacity. Rural housing and villa projects, village roads, small bridges, warehouses, water works, and hillside sites all benefit from a unit that mixes locally and pumps through restricted access.",
          "Compared with pairing a stationary mixer and a separate trailer pump, the combined machine occupies less yard space, needs fewer people to run a continuous pour, and relocates more easily between jobs. Diesel models handle remote grids; electric models cut fuel cost where three-phase power is reliable."
        ]
      },
      {
        "heading": "Diesel or electric—match power to the site",
        "paragraphs": [
          "Diesel concrete mixer pumps are the practical choice for sites without stable electricity, long working days off-grid, or frequent moves between rural locations. A robust diesel package keeps mixing and pumping power consistent under load.",
          "Electric models suit industrial parks, urban sites with permanent three-phase supply, and buyers who prioritize lower running cost and quieter operation. KEWAN configures both options so you select power type by site conditions—not by a one-size catalog default."
        ]
      }
    ],
    "componentGroups": {
      "heading": "Core systems engineered for continuous mix-and-pump cycles",
      "groups": [
        {
          "title": "Power & hydraulic package",
          "items": [
            "Main oil pump: Kawasaki 112 (DMP40) / Kawasaki 140 (DMP50) for stable hydraulic flow under load.",
            "Power packages: diesel 76 kW or electric 45 kW on DMP40; diesel 85 kW or electric 55 kW on DMP50.",
            "Taiwan TO hydraulic valves for precise pressure and direction control during continuous pumping.",
            "Hydraulic oil filter plus overflow six-port lubrication distributor for cleaner oil and timed greasing of wear points.",
            "Delivery cylinders sized to model: 180×1000 mm (DMP40) / 200×1120 mm (DMP50)."
          ]
        },
        {
          "title": "Mixing & delivery package",
          "items": [
            "Integrated mixer-pump layout with S-pipe valve and hopper for continuous on-site mix-and-pump cycles.",
            "Max theoretical output 35 m³/h (DMP40) / 45 m³/h (DMP50) at 12 MPa outlet pressure.",
            "Max aggregate size 30 mm (DMP40) / 40 mm (DMP50); designed for concrete slump 140–230 mm.",
            "Pipeline options Ø80 / 100 / 125 mm to match site layout and pour distance.",
            "Vertical reach up to 100 m / 150 m and horizontal reach up to 300 m / 400 m (DMP40 / DMP50, theoretical)."
          ]
        },
        {
          "title": "Control, sensing & structure",
          "items": [
            "Central control system with remote and electric cabinet for mixer and pump operation from a safe position.",
            "Hopper capacity 0.6 m³ with 1200 mm feeding height for loader-friendly charging.",
            "Towable main frame (1 unit chassis) for site-to-site moves without a full mixer truck.",
            "Compact overall size: about 5400×2100×2300 mm (DMP40) / 5400×2200×2300 mm (DMP50); weight 5000 / 5500 kg."
          ]
        }
      ]
    },
    "reasons": {
      "heading": "Why contractors choose a KEWAN mixer pump",
      "bullets": [
        "True one-unit workflow: mix and pump on the same chassis so you reduce equipment count, yard space, and crew handoffs between mixer and pump.",
        "Built for real access limits: compact trailer form factors suit rural roads, tight urban plots, and multi-site contractors who move often.",
        "Hydraulic cleanliness and factory pressure testing before shipment help reduce early failures and keep oil systems cleaner in service.",
        "Power options for the job: diesel for weak grids and remote pours; electric for lower operating cost where power is stable.",
        "Wear-focused wet-end parts (S-valve, spectacle plate, cutting ring) and heavy pipeline kits are specified for abrasive mixes and daily commercial use—not showroom demos only."
      ]
    },
    "buyingTips": {
      "heading": "How to select the right concrete mixer pump",
      "bullets": [
        "Output first: size theoretical pumping capacity (m³/h) to your longest pour day, then check that mixer production can feed the pump without long idle gaps.",
        "Aggregate size: DMP40 is rated for up to 30 mm stone; DMP50 up to 40 mm—match the model to your mix design to reduce blockage risk.",
        "Power type: diesel (76 / 85 kW) for remote or unstable electricity; electric (45 / 55 kW) for fixed sites with three-phase supply and lower fuel spend.",
        "Reach: check theoretical max—DMP40 about 100 m vertical / 300 m horizontal; DMP50 about 150 m vertical / 400 m horizontal—then derate for elbows, pipe diameter, and mix.",
        "Workability: KEWAN mixer pumps are specified for concrete slump 140–230 mm. Very dry mixes raise blockage risk; overly wet mixes can hurt strength and pressure control.",
        "Crew model: count loading, cement handling, remote operation, and pipeline crew together. A well-set mixer pump often runs with a small team when remote control is used correctly.",
        "Optional accuracy: if volumetric drum feeding is not precise enough for your specs, ask about pairing with a mobile batching plant or loader workflow for better material control."
      ]
    },
    "related": {
      "heading": "Related KEWAN concrete pumps",
      "items": [
        {
          "title": "Concrete Trailer Pump",
          "href": "/concrete-pumps/trailer-concrete-pump/",
          "img": "/images/2025/04/trailer-concrete-pump.png"
        },
        {
          "title": "Truck-Mounted Concrete Pump",
          "href": "/concrete-pumps/truck-mounted-concrete-pump/",
          "img": "/images/2025/04/trailer-concrete-pump.png"
        },
        {
          "title": "Concrete Mixer Pump",
          "href": "/concrete-pumps/concrete-mixer-pump/",
          "img": "/images/2025/03/concrete-mixer-pump.png"
        }
      ]
    },
    "support": {
      "heading": "Support that stays with the machine after delivery",
      "columns": [
        {
          "title": "Before you buy",
          "bullets": [
            "Project-based model selection (output, reach, power type)",
            "Side-by-side technical comparison of diesel vs electric options",
            "Guidance on pipeline layout and typical crew setup",
            "Clear quotation scope: machine, wear parts, and recommended spares"
          ]
        },
        {
          "title": "After you order",
          "bullets": [
            "Factory test records and shipping preparation",
            "Remote commissioning guidance and on-site support options",
            "Warranty coverage on major components (excluding normal wear parts)",
            "Wear-parts supply planning so glasses, cutting rings, and seals stay available",
            "Door-to-port logistics coordination to your destination"
          ]
        }
      ]
    },
    "faq": {
      "heading": "FAQ — KEWAN concrete mixer pumps",
      "items": [
        {
          "q": "What horizontal and vertical pumping distances can I expect?",
          "a": "Theoretical max: DMP40 about 300 m horizontal / 100 m vertical; DMP50 about 400 m horizontal / 150 m vertical. Actual reach depends on mix design, pipe diameter (Ø80/100/125 mm), number of elbows, and site layout. Share your pour height and run length for a project-specific recommendation."
        },
        {
          "q": "What hopper capacity does the machine have?",
          "a": "Hopper capacity is 0.6 m³ with a feeding height of 1200 mm on both DMP40 and DMP50, convenient for loader charging."
        },
        {
          "q": "How much concrete can be pumped per hour?",
          "a": "Max theoretical output is 35 m³/h on DMP40 and 45 m³/h on DMP50 at 12 MPa outlet pressure. Actual daily volume depends on loading speed, mix, pipeline, and crew coordination."
        },
        {
          "q": "Can the unit handle 40 mm aggregates?",
          "a": "DMP50 is rated for max aggregate 40 mm. DMP40 is rated for 30 mm. Choose the model that matches your stone size and keep slump in the 140–230 mm range for reliable pumping."
        },
        {
          "q": "Can mixing and pumping be used independently?",
          "a": "Yes. You can pump ready-mixed concrete from a transit mixer when on-site production is not enough, or add a second mixer if you need higher continuous volume. Mixing-only use is also possible when pipeline placement is not required."
        },
        {
          "q": "How many operators are needed?",
          "a": "A typical continuous pour uses a small crew—often around five people: loader operator, remote operator, cement handling, and two people on pipeline placement. Mixer and pump can be managed from the central control system with remote to simplify operation."
        },
        {
          "q": "What is the usual delivery lead time?",
          "a": "Diesel units are often ready in about 7–10 days when stocked configuration is ordered. Electric units with special voltage requirements typically need about 20–25 days. Confirm lead time with your order details."
        },
        {
          "q": "Is diesel or electric better for my project?",
          "a": "Choose diesel (76 kW on DMP40 / 85 kW on DMP50) for remote sites or unstable power. Choose electric (45 kW / 55 kW) when reliable three-phase power is available and you want lower fuel cost and quieter operation. We help match power type to your site constraints and daily hours."
        }
      ]
    },
    "specTable": {
      "caption": "Mixer pump technical parameters",
      "headers": ["Parameter", "DMP40", "DMP50"],
      "rows": [
        ["Max. theoretical output", "35 m³/h", "45 m³/h"],
        ["Max. aggregate size", "30 mm", "40 mm"],
        ["Outlet pressure", "12 MPa", "12 MPa"],
        ["Vertical delivery distance", "100 m", "150 m"],
        ["Horizontal delivery distance", "300 m", "400 m"],
        ["Power", "Diesel 76 kW\nElectric 45 kW", "Diesel 85 kW\nElectric 55 kW"],
        ["Hopper / feeding height", "0.6 m³ / 1200 mm", "0.6 m³ / 1200 mm"],
        ["Delivery pipe diameter", "80 / 100 / 125 mm", "80 / 100 / 125 mm"],
        ["Concrete slump", "140–230 mm", "140–230 mm"],
        ["Towable main frame", "1 unit", "1 unit"],
        ["S-pipe / hopper / mixer", "S-pipe / hopper", "S-pipe / hopper"],
        ["Delivery cylinder / oil cylinder", "180×1000 mm", "200×1120 mm"],
        ["Hydraulic valve", "Taiwan TO", "Taiwan TO"],
        ["Hydraulic oil filter", "1 unit", "1 unit"],
        ["Hydraulic lubrication assembly", "Overflow six-port distributor", "Overflow six-port distributor"],
        ["Remote / electric cabinet", "Central control system", "Central control system"],
        ["Main oil pump", "Kawasaki 112", "Kawasaki 140"],
        ["Motor / diesel engine", "45 kW / 76 kW", "55 kW / 85 kW"],
        ["Overall dimensions (L×W×H)", "5400×2100×2300 mm", "5400×2200×2300 mm"],
        ["Overall weight", "5000 kg", "5500 kg"]
      ]
    },
    "projects": {
      "heading": "KEWAN concrete machinery projects",
      "items": [
        {
          "title": "Concrete mixer pump deployed for multi-site housing pours",
          "href": "#",
          "img": "/images/2025/08/concrete-mixer-pump-indonesia.jpg",
          "year": "2025"
        },
        {
          "title": "Trailer pump support on mid-rise building construction",
          "href": "#",
          "img": "/images/2025/04/trailer-concrete-pump.png",
          "year": "2025"
        },
        {
          "title": "Self-loading mixer shipped for remote-site production",
          "href": "#",
          "img": "/images/2025/11/Daswell-SLM4-for-Indonesian-Customer-1024x576.jpg",
          "year": "2025"
        }
      ]
    }
  },
  "trailer-concrete-pump": {
    "slug": "trailer-concrete-pump",
    "title": "Concrete Trailer Pump",
    "breadcrumb": [
      { "text": "Home", "href": "/" },
      { "text": "Concrete Pumps", "href": "/concrete-pumps/" },
      { "text": "Concrete Trailer Pump" }
    ],
    "intro": {
      "paragraphs": [
        "A trailer concrete pump (also called a trailer-mounted line pump, drag pump, or stationary concrete pump) places ready-mixed concrete exactly where your pour needs it — through pipelines you lay across the job site. The unit stays in one working position while concrete travels horizontally and vertically to foundations, slabs, tunnels, bridges, and high-rise decks.",
        "KEWAN builds diesel and electric trailer pumps for contractors who want steady output, straightforward operation, and equipment that earns its keep on small jobs, mid-size commercial work, and demanding infrastructure projects. Multiple capacity grades are available so you can match the machine to your daily volume and pipeline layout — not the other way around."
      ],
      "keySpecs": [
        { "label": "Max. theoretical output", "value": "15–90 m³/h" },
        { "label": "Outlet pressure", "value": "6–18 MPa" },
        { "label": "Power options", "value": "Diesel / Electric" }
      ],
      "image": "/images/trailer-pump-side-view.png",
      "imageAlt": "Trailer Concrete Pump",
      "buttons": [
        { "text": "Message", "href": "#request-quote" },
        { "text": "Send Email", "href": "mailto:global@kewan.com" }
      ]
    },
    "featureBlocks": [
      {
        "heading": "What Makes This Solution Different On Site",
        "bullets": [
          "Trailer mobility, fixed pumping point — Tow the pump to the job; connect pipe and hose runs to reach pours that mixers alone cannot serve.",
          "S-valve distribution — Industry-proven valve geometry for continuous flow and reliable switching between material cylinders.",
          "Open-circuit hydraulics — Mature architecture that field teams know how to service and troubleshoot.",
          "Pipeline flexibility — Extend placement with steel pipe and hose combinations; adapt routing around obstacles, elevation changes, and indoor or confined layouts.",
          "Works with your existing fleet — Often paired with transit mixers, on-site batching, or mixer trucks; no need to replace your whole logistics chain."
        ],
        "image": "/images/2026/06/kewan-trailer-pump-3.jpg",
        "imageAlt": "KEWAN trailer concrete pump product"
      },
      {
        "heading": "How Pumping Works",
        "paragraphs": [
          "1. Power — The diesel engine or electric motor drives the main hydraulic pump, which supplies pressurized oil to the pumping circuit.",
          "2. Alternating cylinders — Hydraulic cylinders move concrete pistons in two material cylinders. While one cylinder pushes concrete into the pipeline, the other draws fresh mix from the hopper. The distribution valve switches in sync so flow stays continuous.",
          "3. Placement — Concrete travels through your pipe and hose network to the formwork, slab, or structural element. The pump stays put; only the pipeline path changes as the pour moves."
        ],
        "image": "/images/2025/04/trailer-pump-working-site.jpg",
        "imageAlt": "Trailer pump on a working site"
      },
      {
        "image": "/images/2026/06/kewan-trailer-pump-4.jpg",
        "imageAlt": "KEWAN trailer concrete pump on site"
      }
    ],
    "componentGroupsAfterBlock": 0,
    "componentGroups": {
      "heading": "Engineering Focus: Built for Uptime",
      "groups": [
        {
          "title": "Power and Drive",
          "items": [
            "Diesel engines from established suppliers for sites without dependable grid power or for outdoor heavy use.",
            "Electric motors for urban and residential jobs where lower noise and zero exhaust at the pour point matter.",
            "Power is sized to drive the main hydraulic package consistently under load — not just to win a spec sheet comparison."
          ]
        },
        {
          "title": "Pumping and Hydraulics",
          "items": [
            "Main hydraulic pump and delivery cylinders matched to rated output and pressure class.",
            "High / low pressure switching where applicable so you can balance distance and volume as the pour progresses.",
            "Premium hydraulic hose and fittings to reduce leakage risk and unplanned downtime."
          ]
        },
        {
          "title": "Distribution and Wear Parts",
          "items": [
            "S-tube valve with hardened spectacle plate and cutting ring — the wear pair that defines maintenance rhythm.",
            "Wear surfaces treated for longer intervals between replacements; parts designed for straightforward field change-out."
          ]
        },
        {
          "title": "Hopper and Agitation",
          "items": [
            "Stirring mechanism keeps the mix moving and feed consistent.",
            "Hopper geometry aimed at stable feeding and reduced spillage during continuous operation."
          ]
        },
        {
          "title": "Cooling, Filtration, and Lubrication",
          "items": [
            "Oil filtration and cooling protect the hydraulic package in hot climates and long shifts.",
            "Centralized lubrication on critical points so daily greasing does not depend on operator memory alone."
          ]
        },
        {
          "title": "Control and Safety",
          "items": [
            "Industrial-grade electrical components for reliable interlocks and sequence control.",
            "Clear operating logic so crews can train quickly and recognize fault conditions early."
          ]
        }
      ]
    },
    "reasons": {
      "heading": "Where Teams Use Trailer Concrete Pumps",
      "bullets": [
        "Residential & Villas — Foundations, basements, driveways, yard pools — steady feed without bringing a boom truck into tight access.",
        "Commercial & Industrial Floors — Large slab areas where pipeline layout beats repeated truck repositioning.",
        "Bridges, Culverts & Highways — Long horizontal runs and controlled pour rates for structural elements.",
        "Tunnels & Underground Works — Electric options where emissions and noise matter; diesel where grid power is limited.",
        "Hydropower, Mining & Energy Sites — Remote diesel power; durable components for extended shift operation.",
        "High-Rise Structural Pours — When combined with proper pipe support and cleaning discipline, line pumping supports vertical delivery alongside boom solutions."
      ]
    },
    "buyingTips": {
      "heading": "Diesel or Electric: How to Choose",
      "bullets": [
        "Stable three-phase power, noise or emission limits, residential or indoor-adjacent work → Electric trailer pump — quieter at the point of work, no engine exhaust at the hopper.",
        "No grid, remote road or industrial sites, variable outdoor conditions → Diesel trailer pump — self-contained power; plan for engine maintenance in your O&M budget.",
        "Mixed portfolio of jobs — Many contractors run diesel for mobility and power independence; others keep an electric unit for city work. Share your job mix and let us recommend the right machine."
      ]
    },
    "related": {
      "heading": "Explore Other KEWAN Concrete Pumps",
      "items": [
        {
          "title": "Concrete Mixer Pump",
          "href": "/concrete-pumps/concrete-mixer-pump/",
          "img": "/images/2025/03/concrete-mixer-pump.png"
        },
        {
          "title": "Concrete Boom Pump",
          "href": "https://daswell.com/concrete-pumps/concrete-boom-pump/",
          "img": "/images/2025/04/concrete-boom-pump.jpg"
        },
        {
          "title": "Truck-Mounted Concrete Pump",
          "href": "/concrete-pumps/truck-mounted-concrete-pump/",
          "img": "/images/2026/02/trailer-concrete-pump-jpg.webp"
        }
      ]
    },
    "support": {
      "heading": "Why Work with KEWAN",
      "columns": [
        {
          "title": "Capability-First Approach",
          "bullets": [
            "Application-first sizing — We start from your pour schedule, pipeline path, and mix design, not from pushing the largest model in stock.",
            "Configurable builds — Diesel vs electric, component tier, pipe and hose packages, and export voltage can be shaped to your project.",
            "Manufacturing discipline — Production follows documented quality procedures. Critical welds, hydraulic assembly, and test runs are delivery gates, not optional paperwork."
          ]
        },
        {
          "title": "Service That Respects Your Schedule",
          "bullets": [
            "Global logistics experience — Units prepared for container or bulk shipping with packing suited to long-distance transport.",
            "After-sales support — Commissioning guidance, wear parts identification, remote troubleshooting, and spare parts supply.",
            "Honest performance conversations — We prefer you share grade, slump, aggregate size, and pipe layout so expectations match what your crew will see on the first critical pour."
          ]
        }
      ]
    },
    "specTable": {
      "caption": "Technical Data:",
      "headers": [
        "Parameter", "Unit", "HBT20", "HBT30", "HBT40", "HBT50", "HBT60", "HBT80", "HBT90"
      ],
      "rows": [
        [ "Max. Theoretical Output", "m³/h", "15", "25", "35", "45", "60", "80", "90" ],
        [ "Max. Aggregate Size", "mm", "20", "30", "30", "40", "40", "40", "40" ],
        [ "Outlet Pressure", "MPa", "6", "10", "12", "12", "13", "16", "18" ],
        [ "Vertical Conveying Distance", "m", "50", "80", "100", "150", "180", "200", "250" ],
        [ "Horizontal Conveying Distance", "m", "100", "200", "300", "400", "500", "600", "800" ],
        [ "Power", "kW", "Diesel 40\nElectric 22", "Diesel 66\nElectric 37", "Diesel 76\nElectric 45", "Diesel 90\nElectric 55", "Diesel 129\nElectric 90", "Diesel 176\nElectric 110", "Diesel 196\nElectric 162" ],
        [ "Hopper Capacity / Feeding Height", "m³/mm", "0.3/1000", "0.5/1200", "0.6/1200", "0.6/1200", "0.6/1200", "0.6/1200", "0.6/1200" ],
        [ "Delivery Pipe Diameter", "mm", "80/100", "80/100/125", "80/100/125", "80/100/125", "80/100/125", "80/100/125", "80/100/125" ],
        [ "Concrete Slump", "mm", "140–230", "140–230", "140–230", "140–230", "140–230", "140–230", "140–230" ],
        [ "Overall Dimension", "mm", "3000×1400×1500", "3900×1500×1600", "4200×1600×1600", "4300×1600×1600", "4500×1800×1750", "6300×2100×2500", "6300×2100×2500" ],
        [ "Total Weight", "kg", "1000", "1700", "2000", "2500", "5000", "6000", "6500" ]
      ]
    },
    "projects": {
      "heading": "KEWAN Concrete Machinery Projects",
      "items": [
        {
          "title": "Philippine Customer Used a KEWAN Trailer Concrete Pump for Building Construction, 2025",
          "href": "#",
          "img": "/images/2025/08/concrete-mixer-pump-indonesia.jpg",
          "year": "2025"
        },
        {
          "title": "KEWAN SLM4 Self Loading Concrete Mixer in Merauke, Papua, 2023",
          "href": "#",
          "img": "/images/2025/11/Daswell-SLM4-for-Indonesian-Customer-1024x576.jpg",
          "year": "2023"
        },
        {
          "title": "KEWAN Concrete Trailer Pump Project",
          "href": "#",
          "img": "/images/2026/06/kewan-trailer-pump-4.jpg",
          "year": null
        }
      ]
    }
  }
};
