import type { ProductData } from "@/types/product";

// Product content extracted from daswell.com. Generated by scripts/gen-products.py.
export const products: Record<string, ProductData> = {
  "concrete-mixer-pump": {
    "slug": "concrete-mixer-pump",
    "title": "Concrete Mixer Pump",
    "breadcrumb": [
      {
        "text": "Home",
        "href": "/"
      },
      {
        "text": "Concrete Pumps",
        "href": "https://daswell.com/concrete-pumps/"
      },
      {
        "text": "Concrete Mixer Pump"
      }
    ],
    "intro": {
      "paragraphs": [
        "The concrete mixer pump is an innovative construction machine that combines concrete mixing and pumping functions in one machine, completing the work of two machines in the past.",
        "Concrete mixer with pump saves manpower and is more economical, allowing builders to complete concrete pouring tasks more quickly, and is very suitable for small and medium-sized projects such as house construction, road paving and tunnel construction.",
        "The KEWAN concrete mixer pump has high pumping capacity, stable performance and flexible mobility, providing a reliable solution for modern construction sites and has won a lot of praise from users."
      ],
      "keySpecs": [
        {
          "label": "Theoretical pumping capacity",
          "value": "30-45m³/h"
        },
        {
          "label": "Power",
          "value": "Diesel engine / Electric motor"
        }
      ],
      "image": "/images/2025/03/concrete-mixer-pump.png",
      "imageAlt": "Concrete mixer pump",
      "buttons": [
        {
          "text": "Message",
          "href": "#request-quote"
        },
        {
          "text": "Send Email",
          "href": "mailto:global@daswell.com"
        },
        {
          "text": "PDF Download",
          "href": "https://daswell.com/wp-content/uploads/2025/06/concrete-mixer-pump-pdf-brochure.pdf"
        }
      ]
    },
    "featureBlocks": [
      {
        "heading": "KEWAN Efficient Concrete Mixer Pump for Maximum Productivity",
        "paragraphs": [
          "The concrete mixer pump is a machine that combines the functions of a concrete mixer and a concrete pump into one machine, allowing concrete to be mixed at the construction site and then pumped to the desired location. The innovation of combining mixing and pumping in one simplifies the concrete production process, especially in cases of inconvenient transportation or small projects. The loader can easily feed sand, stone, cement, and other raw materials into the hopper. Compared with traditional concrete mixers and concrete mixer pumps, it is easier and faster to complete the work, more economical, and more practical. It is a new and improved equipment.",
          "The mixer pump machine can discharge the mixed concrete directly into the integrated pumping hopper. And our high-performance concrete mixer hydraulic pumping system can deliver it exactly where needed. With KEWAN concrete mixer pump equipment, you can save time, labor, and costs on your job site."
        ],
        "image": "/images/2025/04/main-parts-details-of-concrete-mixer-pump.jpg",
        "imageAlt": "Main parts details of concrete mixer pump"
      }
    ],
    "componentGroups": {
      "heading": "Delicate Components of KEWAN Concrete Mixer Pumps for Efficient Work",
      "groups": [
        {
          "title": "Power and Hydraulic System",
          "items": [
            "Our concrete mixer pumps are engineered with advanced components for making sure high quality. These machines have unmatched reliability, efficiency, and durability. Here you can learn these advanced systems to know them better.",
            "Main Oil Pump. We utilize premium imported options—Kawasaki (Korea) or Rexroth for superior hydraulic performance.",
            "Diesel Engine. It is powered by a robust Weichai diesel engine. It can ensure consistent power delivery in demanding conditions.",
            "Open-Loop Hydraulic System. It ensures smooth operation with minimal energy loss.",
            "100μm Suction Oil Filter. This oil filter has high-precision filtration for protecting critical components.",
            "Aerospace-Grade Cooler. It ensures optimal hydraulic oil temperature for peak efficiency.",
            "Italy Manuli Oil Hoses. It is a premium hydraulic hose for leak-free performance.",
            "Taiwan Yuken Hydraulic Valves. These hydraulic valves can control the system precisely for smooth operation."
          ]
        },
        {
          "title": "Mixing and Delivery System",
          "items": [
            "China’s Number 1 Mixing Motor. This motor delivers powerful, consistent mixing performance.",
            "Reinforced Mixing Blades and Shaft. Whether for the left/ or right half-shaft, hardness reaches HB250-280 for maximum wear resistance.",
            "Brand Swing Cylinder and S-Valve. For these two parts, we use a precise design for smooth concrete flow.",
            "Wear-Resistant Glass Plate and Cutting Ring. These are made from special alloy materials for extended service life.",
            "Full Range of Pipes Included. It is compatible with various working conditions for seamless concrete placement.",
            "450L Large Capacity. Maximizes batch efficiency.",
            "Dual Hydraulic Motors. Utilizing this motor, it has a faster driving speed and 30% higher mixing efficiency than standard models."
          ]
        },
        {
          "title": "Control and Safety System",
          "items": [
            "Japan Omron Relays. It is the industry-leading system. That ensures reliability for electrical safety.",
            "High-Quality Proximity Switches. It ensures accurate sensor performance.",
            "250mm Thickened Drum Steel. It adopts an integrated design for superior structural stability."
          ]
        }
      ]
    },
    "reasons": {
      "heading": "5 Reasons You Should Choose KEWAN Concrete Mixer Pump Manufacturer",
      "bullets": [
        "Premium Hydraulic System Protection: Our hydraulic oil tank uses specially treated steel pipes to prevent corrosion and extend system life. For the oil tank cleaning, the hoses and valve blocks underg",
        "Ultra-Clean Diesel and Hydraulic System: The diesel cleaning port is heat-treated and blown with compressed air. It removes all impurities, guaranteeing cleaner oil quality. By maintaining pure hydrau",
        "Rigorous Pre-Delivery Testing: Before shipment, we utilize high, medium, and low-pressure testing for making sure the machine works stably with leak-free operation. We verify the performance under rea",
        "Enhanced Power Stability: Our mobile concrete mixer pumps include voltage and current stabilization features. It can protect against power fluctuations for uninterrupted operation.",
        "Heavy-Duty Pumping Pipes for Maximum Efficiency: The concrete mixer pumps have 125mm diameter with 4.5mm thickness (5mm at elbows) pipelines. This ensures superior strength and wear resistance. Beside"
      ]
    },
    "buyingTips": {
      "heading": "What You Should Consider When Buying a Concrete Mixer Pump?",
      "bullets": [
        "Making sure the pumping capacity(output volume)you need. The pumping capacity is measured in cubic meters per hour(m³/h). It determines how much concrete the pumping machine can deliver. You should ma",
        "Making sure the maximum aggregate sizes of your materials and pumping machines. The concrete pump with mixer must handle the maximum stones or aggregate size in your concrete mix. If you do not know w",
        "Choosing the power type: diesel or electric. The diesel engine is best for remote job sites without reliable electricity. It can offer high power and mobility. And the electric motor is more cost-effe",
        "Making sure the pumping distance(both vertical and horizontal reach) is. Ensuring the pumps can meet your maximum required distance avoids inefficiencies. FYI, the vertical pumping height is mainly us",
        "Making sure the concrete slump(workability). The ideal slump for pumping is about 100mm or higher. It makes concrete flow smoothly. The low-slump mixes, which is below 50mm may cause blockages. If the"
      ]
    },
    "related": {
      "heading": "Different Types of KEWAN Concrete Pump",
      "items": [
        {
          "title": "Concrete Trailer Pump",
          "href": "/concrete-pumps/trailer-concrete-pump/",
          "img": "/images/2025/04/trailer-concrete-pump.png"
        },
        {
          "title": "Concrete Boom Pump",
          "href": "https://daswell.com/concrete-pumps/concrete-boom-pump/",
          "img": "/images/2025/04/concrete-boom-pump.jpg"
        },
        {
          "title": "Concrete Mixer Pump",
          "href": "https://daswell.com/concrete-pumps/pan-mixer-concrete-pump/",
          "img": "/images/2025/04/concrete-pan-mixer-pump-scaled-e1745542374292.png"
        }
      ]
    },
    "support": {
      "heading": "KEWAN Expert Support and Reliable Service for Your Concrete Mixer Pump Investment",
      "columns": [
        {
          "title": "Comprehensive pre-purchase support",
          "bullets": [
            "Equipment selection guidance",
            "Detailed technical comparisons",
            "One-on-one service to match the perfect machine to your project needs",
            "1-Year Warranty covering all components (excluding normal wear parts)",
            "Local After-Sales Network for faster response times",
            "Wear Parts Inventory – Immediate availability of frequently replaced components"
          ]
        },
        {
          "title": "Professional after-sale service",
          "bullets": [
            "On-call engineers are ready to troubleshoot",
            "Remote and on-site guidance for setup and operation",
            "Timely Logistics",
            "Guaranteed on-time delivery",
            "Door-to-port shipping to your specified destination"
          ]
        }
      ]
    },
    "faq": {
      "heading": "FAQ about KEWAN Concrete Mixer Pumps Equipment",
      "items": [
        {
          "q": "What are the horizontal and vertical pumping distances of your concrete mixture pump?",
          "a": "Horizontal pumping distance is 200 meters, vertical pumping distance is 50 meters."
        },
        {
          "q": "What is the hopper capacity?",
          "a": "0.8m³"
        },
        {
          "q": "How many cubic meters of concrete can be pumped per hour?",
          "a": "The mixer drum can produce about 20 cubic meters of concrete per hour. The pumping system can pump about 50 cubic meters of concrete per hour."
        },
        {
          "q": "Can your machine pump 40mm aggregates?",
          "a": "Yes, of course."
        },
        {
          "q": "Can the functions of pumping and mixing be used separately?",
          "a": "Yes. If the mixer machine does not produce enough concrete, a concrete mixer truck can be used to transport the commercial concrete for pumping. Or add an additional mixer."
        },
        {
          "q": "How many workers are needed for the whole machine to work?",
          "a": "The whole set of equipment needs only five people to operate. One person is responsible for loading by the forklift, one person is responsible for remote control of the equipment, one person is responsible for putting cement, and two people are responsible for taking over and removing the pipes on the floor. The mixer machine and transfer pump are directly controlled by one remote control, which is simple to operate. Compared with the traditional equipment, there are fewer construction people and the operation is more simple."
        },
        {
          "q": "How long is the delivery time?",
          "a": "If the voltage is different, the delivery time of the electric concrete mixer pump is 20-25 days. The delivery time of diesel concrete mixer pump is usually 7-10 days."
        }
      ]
    },
    "specTable": {
      "caption": "Technical Data:",
      "headers": [
        "Parameter",
        "Unit",
        "EMP40",
        "DMP50"
      ],
      "rows": [
        [
          "Power",
          "kw",
          "45",
          "Weichai diesel engine; 85kw"
        ],
        [
          "Whole machine Length",
          "mm",
          "4250",
          "4680"
        ],
        [
          "Width",
          "mm",
          "2100",
          "2100"
        ],
        [
          "Height",
          "mm",
          "2700",
          "2300"
        ],
        [
          "Weight",
          "kg",
          "4000",
          "4200"
        ],
        [
          "Mixer Mixer model",
          "/",
          "JZM450",
          "JZM450"
        ],
        [
          "Theoretical mixing capacity",
          "m3/h",
          "15-25",
          "15-25"
        ],
        [
          "Maximum aggregate size",
          "mm",
          "40",
          "40"
        ],
        [
          "Working cycle time",
          "s",
          "72",
          "72"
        ],
        [
          "Feeding height",
          "mm",
          "1400",
          "1400"
        ],
        [
          "Hopper capacity",
          "m3",
          "0.65",
          "0.65"
        ],
        [
          "Pumping system Theoretical pumping capacity",
          "m3/h",
          "40",
          "45"
        ],
        [
          "Theoretical pumping pressure",
          "MPa",
          "8",
          "10"
        ],
        [
          "Delivery cylinder",
          "/",
          "200*800",
          "230*800"
        ],
        [
          "Hydraulic system",
          "/",
          "Open",
          "Open"
        ],
        [
          "Distribution valve",
          "/",
          "S valve",
          "S valve"
        ],
        [
          "System pressure",
          "MPa",
          "28",
          "28"
        ],
        [
          "Delivery pipe diameter",
          "mm",
          "125",
          "125"
        ]
      ]
    },
    "projects": {
      "heading": "KEWAN Concrete Machinery Projects",
      "items": [
        {
          "title": "Philippine Customer Used a KEWAN Trailer Concrete Pump for Building Construction, 2025",
          "href": "#",
          "img": "/images/2025/08/concrete-mixer-pump-indonesia.jpg",
          "year": "2025"
        },
        {
          "title": "KEWAN 4m³ Self Loading Concrete Mixer Shipped to Indonesia, 2025",
          "href": "#",
          "img": "/images/2025/11/Daswell-SLM4-for-Indonesian-Customer-1024x576.jpg",
          "year": "2025"
        },
        {
          "title": "KEWAN Efficient Concrete Mixer Pump for Maximum Productivity",
          "href": "#",
          "img": "/images/2025/04/mobile-concrete-batching-plant.jpg",
          "year": null
        },
        {
          "title": "Delicate Components of KEWAN Concrete Mixer Pumps for Efficient Work",
          "href": "#",
          "img": "/images/2025/12/stationary-crushing-plant-philippines5.png",
          "year": null
        }
      ]
    }
  },
  "trailer-concrete-pump": {
    "slug": "trailer-concrete-pump",
    "title": "Concrete Trailer Pump",
    "breadcrumb": [
      { "text": "Home", "href": "/" },
      { "text": "Concrete Pumps", "href": "/concrete-pumps/" },
      { "text": "Concrete Trailer Pump" }
    ],
    "intro": {
      "paragraphs": [
        "A trailer concrete pump (also called a trailer-mounted line pump, drag pump, or stationary concrete pump) places ready-mixed concrete exactly where your pour needs it — through pipelines you lay across the job site. The unit stays in one working position while concrete travels horizontally and vertically to foundations, slabs, tunnels, bridges, and high-rise decks.",
        "KEWAN builds diesel and electric trailer pumps for contractors who want steady output, straightforward operation, and equipment that earns its keep on small jobs, mid-size commercial work, and demanding infrastructure projects. Multiple capacity grades are available so you can match the machine to your daily volume and pipeline layout — not the other way around."
      ],
      "keySpecs": [
        { "label": "Max. theoretical output", "value": "15–90 m³/h" },
        { "label": "Outlet pressure", "value": "6–18 MPa" },
        { "label": "Power options", "value": "Diesel / Electric" }
      ],
      "image": "/images/trailer-pump-side-view.png",
      "imageAlt": "Trailer Concrete Pump",
      "buttons": [
        { "text": "Message", "href": "#request-quote" },
        { "text": "Send Email", "href": "mailto:global@kewan.com" }
      ]
    },
    "featureBlocks": [
      {
        "heading": "What Makes This Solution Different On Site",
        "bullets": [
          "Trailer mobility, fixed pumping point — Tow the pump to the job; connect pipe and hose runs to reach pours that mixers alone cannot serve.",
          "S-valve distribution — Industry-proven valve geometry for continuous flow and reliable switching between material cylinders.",
          "Open-circuit hydraulics — Mature architecture that field teams know how to service and troubleshoot.",
          "Pipeline flexibility — Extend placement with steel pipe and hose combinations; adapt routing around obstacles, elevation changes, and indoor or confined layouts.",
          "Works with your existing fleet — Often paired with transit mixers, on-site batching, or mixer trucks; no need to replace your whole logistics chain."
        ],
        "image": "/images/2026/06/kewan-trailer-pump-3.jpg",
        "imageAlt": "KEWAN trailer concrete pump product"
      },
      {
        "heading": "How Pumping Works",
        "paragraphs": [
          "1. Power — The diesel engine or electric motor drives the main hydraulic pump, which supplies pressurized oil to the pumping circuit.",
          "2. Alternating cylinders — Hydraulic cylinders move concrete pistons in two material cylinders. While one cylinder pushes concrete into the pipeline, the other draws fresh mix from the hopper. The distribution valve switches in sync so flow stays continuous.",
          "3. Placement — Concrete travels through your pipe and hose network to the formwork, slab, or structural element. The pump stays put; only the pipeline path changes as the pour moves."
        ],
        "image": "/images/2025/04/trailer-pump-working-site.jpg",
        "imageAlt": "Trailer pump on a working site"
      },
      {
        "image": "/images/2026/06/kewan-trailer-pump-4.jpg",
        "imageAlt": "KEWAN trailer concrete pump on site"
      }
    ],
    "componentGroupsAfterBlock": 0,
    "componentGroups": {
      "heading": "Engineering Focus: Built for Uptime",
      "groups": [
        {
          "title": "Power and Drive",
          "items": [
            "Diesel engines from established suppliers for sites without dependable grid power or for outdoor heavy use.",
            "Electric motors for urban and residential jobs where lower noise and zero exhaust at the pour point matter.",
            "Power is sized to drive the main hydraulic package consistently under load — not just to win a spec sheet comparison."
          ]
        },
        {
          "title": "Pumping and Hydraulics",
          "items": [
            "Main hydraulic pump and delivery cylinders matched to rated output and pressure class.",
            "High / low pressure switching where applicable so you can balance distance and volume as the pour progresses.",
            "Premium hydraulic hose and fittings to reduce leakage risk and unplanned downtime."
          ]
        },
        {
          "title": "Distribution and Wear Parts",
          "items": [
            "S-tube valve with hardened spectacle plate and cutting ring — the wear pair that defines maintenance rhythm.",
            "Wear surfaces treated for longer intervals between replacements; parts designed for straightforward field change-out."
          ]
        },
        {
          "title": "Hopper and Agitation",
          "items": [
            "Stirring mechanism keeps the mix moving and feed consistent.",
            "Hopper geometry aimed at stable feeding and reduced spillage during continuous operation."
          ]
        },
        {
          "title": "Cooling, Filtration, and Lubrication",
          "items": [
            "Oil filtration and cooling protect the hydraulic package in hot climates and long shifts.",
            "Centralized lubrication on critical points so daily greasing does not depend on operator memory alone."
          ]
        },
        {
          "title": "Control and Safety",
          "items": [
            "Industrial-grade electrical components for reliable interlocks and sequence control.",
            "Clear operating logic so crews can train quickly and recognize fault conditions early."
          ]
        }
      ]
    },
    "reasons": {
      "heading": "Where Teams Use Trailer Concrete Pumps",
      "bullets": [
        "Residential & Villas — Foundations, basements, driveways, yard pools — steady feed without bringing a boom truck into tight access.",
        "Commercial & Industrial Floors — Large slab areas where pipeline layout beats repeated truck repositioning.",
        "Bridges, Culverts & Highways — Long horizontal runs and controlled pour rates for structural elements.",
        "Tunnels & Underground Works — Electric options where emissions and noise matter; diesel where grid power is limited.",
        "Hydropower, Mining & Energy Sites — Remote diesel power; durable components for extended shift operation.",
        "High-Rise Structural Pours — When combined with proper pipe support and cleaning discipline, line pumping supports vertical delivery alongside boom solutions."
      ]
    },
    "buyingTips": {
      "heading": "Diesel or Electric: How to Choose",
      "bullets": [
        "Stable three-phase power, noise or emission limits, residential or indoor-adjacent work → Electric trailer pump — quieter at the point of work, no engine exhaust at the hopper.",
        "No grid, remote road or industrial sites, variable outdoor conditions → Diesel trailer pump — self-contained power; plan for engine maintenance in your O&M budget.",
        "Mixed portfolio of jobs — Many contractors run diesel for mobility and power independence; others keep an electric unit for city work. Share your job mix and let us recommend the right machine."
      ]
    },
    "related": {
      "heading": "Explore Other KEWAN Concrete Pumps",
      "items": [
        {
          "title": "Concrete Mixer Pump",
          "href": "/concrete-pumps/concrete-mixer-pump/",
          "img": "/images/2025/03/concrete-mixer-pump.png"
        },
        {
          "title": "Concrete Boom Pump",
          "href": "https://daswell.com/concrete-pumps/concrete-boom-pump/",
          "img": "/images/2025/04/concrete-boom-pump.jpg"
        },
        {
          "title": "Truck-Mounted Concrete Pump",
          "href": "/concrete-pumps/truck-mounted-concrete-pump/",
          "img": "/images/2026/02/trailer-concrete-pump-jpg.webp"
        }
      ]
    },
    "support": {
      "heading": "Why Work with KEWAN",
      "columns": [
        {
          "title": "Capability-First Approach",
          "bullets": [
            "Application-first sizing — We start from your pour schedule, pipeline path, and mix design, not from pushing the largest model in stock.",
            "Configurable builds — Diesel vs electric, component tier, pipe and hose packages, and export voltage can be shaped to your project.",
            "Manufacturing discipline — Production follows documented quality procedures. Critical welds, hydraulic assembly, and test runs are delivery gates, not optional paperwork."
          ]
        },
        {
          "title": "Service That Respects Your Schedule",
          "bullets": [
            "Global logistics experience — Units prepared for container or bulk shipping with packing suited to long-distance transport.",
            "After-sales support — Commissioning guidance, wear parts identification, remote troubleshooting, and spare parts supply.",
            "Honest performance conversations — We prefer you share grade, slump, aggregate size, and pipe layout so expectations match what your crew will see on the first critical pour."
          ]
        }
      ]
    },
    "specTable": {
      "caption": "Technical Data:",
      "headers": [
        "Parameter", "Unit", "HBT20", "HBT30", "HBT40", "HBT50", "HBT60", "HBT80", "HBT90"
      ],
      "rows": [
        [ "Max. Theoretical Output", "m³/h", "15", "25", "35", "45", "60", "80", "90" ],
        [ "Max. Aggregate Size", "mm", "20", "30", "30", "40", "40", "40", "40" ],
        [ "Outlet Pressure", "MPa", "6", "10", "12", "12", "13", "16", "18" ],
        [ "Vertical Conveying Distance", "m", "50", "80", "100", "150", "180", "200", "250" ],
        [ "Horizontal Conveying Distance", "m", "100", "200", "300", "400", "500", "600", "800" ],
        [ "Power", "kW", "Diesel 40 / Electric 22", "Diesel 66 / Electric 37", "Diesel 76 / Electric 45", "Diesel 90 / Electric 55", "Diesel 129 / Electric 90", "Diesel 176 / Electric 110", "Diesel 196 / Electric 162" ],
        [ "Hopper Capacity / Feeding Height", "m³/mm", "0.3/1000", "0.5/1200", "0.6/1200", "0.6/1200", "0.6/1200", "0.6/1200", "0.6/1200" ],
        [ "Delivery Pipe Diameter", "mm", "80/100", "80/100/125", "80/100/125", "80/100/125", "80/100/125", "80/100/125", "80/100/125" ],
        [ "Concrete Slump", "mm", "140–230", "140–230", "140–230", "140–230", "140–230", "140–230", "140–230" ],
        [ "Overall Dimension", "mm", "3000×1400×1500", "3900×1500×1600", "4200×1600×1600", "4300×1600×1600", "4500×1800×1750", "6300×2100×2500", "6300×2100×2500" ],
        [ "Total Weight", "kg", "1000", "1700", "2000", "2500", "5000", "6000", "6500" ]
      ]
    },
    "projects": {
      "heading": "KEWAN Concrete Machinery Projects",
      "items": [
        {
          "title": "Philippine Customer Used a KEWAN Trailer Concrete Pump for Building Construction, 2025",
          "href": "#",
          "img": "/images/2025/08/concrete-mixer-pump-indonesia.jpg",
          "year": "2025"
        },
        {
          "title": "KEWAN SLM4 Self Loading Concrete Mixer in Merauke, Papua, 2023",
          "href": "#",
          "img": "/images/2025/11/Daswell-SLM4-for-Indonesian-Customer-1024x576.jpg",
          "year": "2023"
        },
        {
          "title": "KEWAN Concrete Trailer Pump Project",
          "href": "#",
          "img": "/images/2026/06/kewan-trailer-pump-4.jpg",
          "year": null
        }
      ]
    }
  }
};
